version: '3.8'
services:

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-container
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
#    env_file:
#      - .env.docker
    networks:
      - blogging_platform_my_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.1:3307/blogging
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password



  mysqldb:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_DATABASE=blogging
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - blogging_platform_my_network
    restart: unless-stopped


volumes:
  mysql-data:
    driver: local

networks:
  blogging_platform_my_network:
    driver: bridge