services:

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-container
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    env_file:
      - .env.docker
    networks:
      - blogging_platform_my_network
    environment:
      #      SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.1:3307/blogging
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      #      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      #      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}



  mysqldb:
    image: mysql:8.1
    container_name: mysql
    environment:
#      - MYSQL_DATABASE=blogging
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
#      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - blogging_platform_my_network


volumes:
  mysql-data:
    driver: local

networks:
  blogging_platform_my_network:
    driver: bridge